wfdb/models.py
from flask_sqlalchemy import SQLAlchemy
from wfdb.extensions import bcrypt, login_manager
from flask_login import UserMixin

db = SQLAlchemy()

tags = db.Table(
    'post_tags',
    db.Column('post_id', db.Integer, db.ForeignKey('post.id')),
    db.Column('tag_id', db.Integer, db.ForeignKey('tag.id'))
)
roles = db.Table(
    'role_users',
    db.Column('user_id', db.Integer, db.ForeignKey('user.id')),
    db.Column('role_id', db.Integer, db.ForeignKey('role.id'))
)
class User(db.Model,UserMixin):
    id = db.Column(db.Integer(), primary_key=True)
    username = db.Column(db.String(), unique=True)
    password = db.Column(db.String())
    active = db.Column(db.Boolean())
    posts = db.relationship('Post', backref='user', lazy='dynamic')
    comments = db.relationship('Comment', backref='user', lazy='dynamic')
    roles = db.relationship(
        'Role',
        secondary=roles,
        backref=db.backref('users', lazy='dynamic')
    )
    def get_id(self):
        return self.id

    def is_active(self):
        return self.ative

    def __repr__(self):
        return '<User {}>'.format(self.username)

    def set_password(self,password):
        self.password = bcrypt.generate_password_hash(password)

    def check_password(self,password):
        return bcrypt.check_password_hash(self.password,password)
        
@login_manager.user_loader
def load_user(userid):
    u=User()
    if u.get_id()==userid:
        return u
    else:
        return None

class Role(db.Model):
    id = db.Column(db.Integer(), primary_key=True)
    name = db.Column(db.String(80), unique=True)
    description = db.Column(db.String(255))


    def __repr__(self):
        return '<Role {}>'.format(self.name)



class Actor(db.Model):
    id = db.Column(db.Integer(), primary_key=True)
    first_name = db.Column(db.String())
    last_name = db.Column(db.String())
    birthday = db.Column(db.Date())
    deathday = db.Column(db.Date())
    hometown = db.Column(db.String())
    bio = db.Column(db.Text())
    picture = db.Column(db.String())
    roles = db.relationship("MovieRole", backref="actor")
    directorships = db.relationship(
        'Movie',
        backref='director',
        lazy='dynamic'
    )

    def __repr__(self):
        return '<Actor {} {}>'.format(self.first_name, self.last_name)


class Movie(db.Model):
    id = db.Column(db.Integer(), primary_key=True)
    name = db.Column(db.String())
    release_date = db.Column(db.Date())
    director_id = db.Column(db.Integer(), db.ForeignKey('actor.id'))
    summary = db.Column(db.Text())

    def __repr__(self):
        return '<Movie {}>'.format(self.name)


class MovieRole(db.Model):
    id = db.Column(db.Integer(), primary_key=True)
    actor_id = db.Column(db.Integer, db.ForeignKey('actor.id'))
    movie_id = db.Column(db.Integer, db.ForeignKey('movie.id'))
    role_name = db.Column(db.String())
    movie = db.relationship("Movie", backref="cast")

    def __repr__(self):
        return '<MovieRole {}>'.format(self.role_name)


class Post(db.Model):
    id = db.Column(db.Integer(), primary_key=True)
    title = db.Column(db.String())
    text = db.Column(db.Text())
    publish_date = db.Column(db.DateTime())
    user_id = db.Column(db.Integer(), db.ForeignKey('user.id'))
    comments = db.relationship(
        'Comment',
        backref='post',
        lazy='dynamic'
    )
    tags = db.relationship(
        'Tag',
        secondary=tags,
        backref=db.backref('posts', lazy='dynamic'),
        lazy='dynamic'
    )

    def __repr__(self):
        return "<Post '{}'>".format(self.title)


class Tag(db.Model):
    id = db.Column(db.Integer(), primary_key=True)
    title = db.Column(db.String())

    def __repr__(self):
        return "<Tag '{}'>".format(self.title)


class Comment(db.Model):
    id = db.Column(db.Integer(), primary_key=True)
    text = db.Column(db.Text())
    date = db.Column(db.DateTime())
    post_id = db.Column(db.Integer(), db.ForeignKey('post.id'))
    user_id = db.Column(db.Integer(), db.ForeignKey('user.id'))

    def __repr__(self):
        return '<Comment {}>'.format(self.text[:15])

wfdb/forms.py
from flask_wtf import Form
from wtforms import TextAreaField, TextField, PasswordField, StringField
from wtforms import validators
from wfdb.models import User

class CommentForm(Form):
    text = TextAreaField(u'Text', validators=[
        validators.required(),
        validators.Length(max=2000)
    ])

class LoginForm(Form):
    username = TextField(
        'Username',
        validators=[validators.DataRequired()]
        )
    password = PasswordField(
        'Password',
        validators=[validators.DataRequired()]
        )

    def validate(self):

        check_validate = super(LoginForm,self).validate()
        if not check_validate:
            return False

        user = User.query.filter_by(username=self.username.data).first()
        if not user:
            self.username.errors.append('Invalid username')
            return False

        if not user.check_password(self.password.data):
            self.password.errors.append('Invalid password')
            return False
        return True

class RegisterForm(Form):
    username = TextField(
        'Username',
        validators=[validators.DataRequired(), validators.Length(max=255)]
        )
    password = PasswordField(
        'Password',
        validators=[validators.DataRequired(), validators.Length(min=8)]
        )
    confirm = PasswordField(
        'Confirm Password',
        validators=[validators.DataRequired(),validators.EqualTo('password')]
        )

    def validate(self):
        check_validate = super(RegisterForm,self).validate()
        if not check_validate:
            return False
        user = User.query.filter_by(username=self.username.data).first()

        if user:
            self.username.errors.append('User with that name alrealy exists')
            return False
        return True

wfdb/__init__.py
from flask import Flask
from wfdb.models import db
from wfdb.controllers.main import main_blueprint
from wfdb.controllers.blog import blog_blueprint
from wfdb.extensions import bcrypt, login_manager

def create_app(config_object):
    app = Flask(__name__)
    app.config.from_object(config_object)

    db.init_app(app)
    login_manager.init_app(app)
    bcrypt.init_app(app)
    app.register_blueprint(main_blueprint)
    app.register_blueprint(blog_blueprint)

    return app

if __name__ == "__main__":
    app.run(debug=True)

wfdb/controllers/blog.py
import datetime
from flask import render_template, Blueprint

from wfdb.models import db, Post, Comment, User
from wfdb.forms import CommentForm


blog_blueprint = Blueprint(
    'blog',
    __name__,
    template_folder='../templates/blog',
    url_prefix="/blog"
)


@blog_blueprint.route("/")
def blog():
    posts = Post.query.order_by(Post.publish_date.desc()).all()

    return render_template("blog.html", posts=posts)


@blog_blueprint.route("/<int:post_id>", methods=["GET", "POST"])
def post(post_id):
    post = Post.query.get_or_404(post_id)
    
    form = CommentForm()
    if form.validate_on_submit():
        comment = Comment()
        comment.text = form.text.data
        comment.date = datetime.datetime.now()
        comment.post = post
        comment.user = User.query.get(1)

        db.session.add(comment)
        db.session.commit()

    return render_template("post.html", post=post, form=form)

wfdb/controllers/main.py
from flask import render_template, Blueprint, redirect, request, flash,url_for
from flask_login import login_user,logout_user, login_required, login_manager

from wfdb.models import Movie, Actor, User, db
from wfdb.forms import LoginForm,RegisterForm

main_blueprint = Blueprint(
    'main',
    __name__,
    template_folder='../templates/main'
)


@main_blueprint.route("/")

def home():
    latest_movies = Movie.query.order_by(
        Movie.release_date.desc()
    ).limit(5).all()

    return render_template("index.html", latest_movies=latest_movies)

@main_blueprint.route("/actor/<int:actor_id>")
@login_required

def actor(actor_id):
    actor = Actor.query.get_or_404(actor_id)

    return render_template("actor.html", actor=actor)


@main_blueprint.route("/movie/<int:movie_id>")
def movie(movie_id):
    movie = Movie.query.get_or_404(movie_id)

    return render_template("movie.html", movie=movie)


@main_blueprint.route("/login",methods=["GET","POST"])
def login():
    form = LoginForm()

    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).one()

        login_user(user)
        return redirect(request.args.get("next") or url_for("main.home"))
        flash("login success",category='success')
    return render_template("login.html",form=form)

@main_blueprint.route("/register",methods=["GET","POST"])
def register():
    form = RegisterForm()

    if form.validate_on_submit():
        user = User()
        print(form.username.data)
        user.username = form.username.data
        user.set_password(form.password.data)
        db.session.add(user)
        db.session.commit()

        flash("Your user has be created please login",category='success')
        return redirect(request.args.get("next") or url_for("main.home"))
    
    return render_template("register.html",form=form)

wfdb/templates/main/actor.html
{% extends "base.html" %}

{% block title %}{{ actor.first_name }} {{ actor.last_name }}'s Page{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-md-4 col-md-offset-2">
            <h1>{{ actor.first_name }} {{ actor.last_name }}</h1>
            <p><strong>Birth Date</strong> {{ actor.birthday }}</p>
            {% if actor.deathday is not none %} <p><strong>Death Date</strong>  {{ actor.deathday }} </p> {% endif %}
            <p><strong>Hometown</strong> {{ actor.hometown }}</p>
        </div>
        <div class="col-md-4">
            <img src="http://placehold.it/250x300">
        </div>
    </div>
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <h2>Bio</h2>
            <p>{{ actor.bio }}</p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <h2>Roles</h2>
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Movie</th>
                        <th>Role</th>
                        <th>Date</th>
                    </tr>
                </thead>
                <tbody>
                    {% for role in actor.roles %}
                        <tr>
                            <td><a href="{{ url_for('main.movie', movie_id=role.movie.id) }}">{{ role.movie.name }}</a></td>
                            <td>{{ role.role_name }}</td>
                            <td>{{ role.movie.release_date }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <h2>Directorships</h2>
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Movie</th>
                        <th>Date</th>
                    </tr>
                </thead>
                <tbody>
                    {% for movie in actor.directorships %}
                        <tr>
                            <td><a href="{{ url_for('main.movie', movie_id=movie.id) }}">{{ movie.name }}</a></td>
                            <td>{{ movie.release_date }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

wfdb/templates/main/index.html
{% extends "base.html" %}

{% block title %}Home{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-md-12">
            <h1 class="text-xs-center">Latest Movies</h1>
        </div>
    </div>
	{% for movie in latest_movies %}
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="media">
                    <div class="media-left">
                        <a href="#">
                            <img class="media-object" src="http://placehold.it/150x150">
                        </a>
                    </div>
                    <div class="media-body">
                        <h4 class="media-heading">{{loop.index}}. {{ movie.name }}</h4>
                        <p>{{ movie.summary | truncate(700) }}</p>
                        <p><a href="{{ url_for('main.movie', movie_id=movie.id) }}">Read More</a></p>
                    </div>
                </div>
            </div>
        </div>
	{% endfor %}
{% endblock %}

wfdb/templates/main/login.html
{%extends "base.html" %}

{% block title%}Login{%endblock title%}
 {% block body %}
          
<div class="row">
    <div class="col-lg-4"></div>
    <div class="col-lg-4">
        
        <form action="{{ url_for('main.login') }}" method="POST" role="form">
            <legend>Form title</legend>
            {{ form.hidden_tag() }}
            <div class="form-group">
                {{ form.username.label}}
                    {% if form.username.errors %}
                        {% for e in form.username.errors %}
                            <p class="form-text">{{ e }}</p>
                        {% endfor %}
                    {% endif %}
                    {{ form.username(class_="form-control")}}
                
            </div>
        <div class="form-group">
                {{ form.password.label}}
                    {% if form.password.errors %}
                        {% for e in form.password.errors %}
                            <p class="form-text">{{ e }}</p>
                        {% endfor %}
                    {% endif %}
                    {{ form.password(class_="form-control")}}
                
            </div>
            
        
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
        

    </div>
</div>
  {% endblock %}

wfdb/templates/main/movie.html
{% extends "base.html" %}

{% block title %}{{ movie.name }}{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-md-4 col-md-offset-2">
            <h1>{{ movie.name }}</h1>
            <p><strong>Release Date</strong> {{ movie.release_date }}</p>
            <p><strong>Director</strong>
              <a href="{{ url_for('main.actor', actor_id=movie.director.id) }}">
                {{ movie.director.first_name }} {{ movie.director.last_name }}
              </a>
            </p>
        </div>
        <div class="col-md-4">
            <img src="http://placehold.it/250x300">
        </div>
        <div class="col-md-2"></div>
    </div>
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <h2>Plot Summary</h2>
            <p>{{ movie.summary }}</p>
        </div>
        <div class="col-md-2"></div>
    </div>
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <h2>Cast</h2>
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Role</th>
                    </tr>
                </thead>
                <tbody>
                    {% for role in movie.cast %}
                    <tr>
                        <td><a href="{{ url_for('main.actor', actor_id=role.actor.id) }}">{{ role.actor.first_name }} {{ role.actor.last_name }}</a></td>
                        <td>{{ role.role_name }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="col-md-2"></div>
    </div>
{% endblock %}

wfdb/templates/main/register.html
{%extends "base.html" %}

{% block title%}Login{%endblock title%}
{% block body %}
<div class="row">
    <div class="col-lg-4"></div>
    <div class="col-lg-4">
        
        <form action="{{ url_for('.register') }}" method="POST" role="form">
            <legend>Form title</legend>
            {{ form.hidden_tag() }}
            <div class="form-group">
                {{ form.username.label}}
                    {% if form.username.errors %}
                        {% for e in form.username.errors %}
                            <p class="form-text">{{ e }}</p>
                        {% endfor %}
                    {% endif %}
                    {{ form.username(class_="form-control")}}
                
            </div>
        <div class="form-group">
                {{ form.password.label}}
                    {% if form.password.errors %}
                        {% for e in form.password.errors %}
                            <p class="form-text">{{ e }}</p>
                        {% endfor %}
                    {% endif %}
                    {{ form.password(class_="form-control")}}
                
            </div>
             <div class="form-group">
                {{ form.confirm.label}}
                    {% if form.confirm.errors %}
                        {% for e in form.confirm.errors %}
                            <p class="form-text">{{ e }}</p>
                        {% endfor %}
                    {% endif %}
                    {{ form.confirm(class_="form-control")}}
                
            </div>
        
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
        

    </div>
</div>
 {% endblock %}